### ISSUE TITLE
more claculations

### ISSUE THREAD

**Issue by gosoccerboy5** [JeffaloBob/claculator#1]
i want to go above n beond 2+3 becase my math techer is giving me hard math prolems :(((((((

**Comment by gosoccerboy5** [comment]
:( 😢 <img src="https://cdn.scratch.mit.edu/scratchr2/static/__7d923c5df7357c1b067e0ad8c2deb8b1__/djangobb_forum/img/smilies/sad.png">

**Comment by Quantum-Codes** [comment]
JS can't add?!
